### ISSUE TITLE
Gather all front-end design documents in one place

### ISSUE THREAD

**Issue by TheCodeSummoner** [ncl-ROVers/surface#11]

**Comment by TheCodeSummoner** [comment]
@hikarthik See the photoshop file and attached screenshots in Microsoft Teams, Systems subsection, Files. Let me know if you can't find it.

https://github.com/ncl-ROVers/surface-2019-20/tree/master/assets might also be helpful, although I doubt it - I had to go with some compromises due to using PySide2 - you should have more space with React.

**Comment by TheCodeSummoner** [comment]
You can open the photoshop file in GIMP if you don't have Photoshop itself. Should be fine in general, may have a few import issues.

**Comment by hikarthik** [comment]
@TheCodeSummoner Thank you!
