### ISSUE TITLE
Research and pick the documentation model/tool

### ISSUE THREAD

**Issue by TheCodeSummoner** [ncl-ROVers/surface#27]
To read about possible documentation tools for Python development which include an automatic website documentation generation. Consider Sphinx.

**Comment by e-km0d** [comment]
Sphinx seems like a viable option for Python code documentation. It uses reStructuredText as its markup language. Sphinx can automatically generate a website for Python code documentation based on docstrings, show individual classes, modules, etc. You can create sections, lists, show code snippets, etc. I am currently reading through the documentation and trying to familiarise myself with its features. It would also be useful to learn the reStructuredText syntax as it is used as the markup language for Sphinx. I would suggest having a look at it yourself but I believe that Sphinx could be a very good option.
