### ISSUE TITLE
Schedule some meetings

### ISSUE THREAD

**Issue by TheCodeSummoner** [ncl-ROVers/surface#31]

**Comment by TheCodeSummoner** [comment]
Proposed meetings time - Friday every 2 weeks at 5 pm - 01/01/2021 first meeting

**Comment by mradzikowski** [comment]
I agree

**Comment by Fisherchloe** [comment]
> Proposed meetings time - Friday every 2 weeks at 5 pm - 01/01/2021 first meeting

**Comment by NekTaf** [comment]
> Proposed meetings time - Friday every 2 weeks at 5 pm - 01/01/2021 first meeting

Sounds good

**Comment by ymber** [comment]
Fridays at 6pm would work better for me.

**Comment by lestherll** [comment]
Fridays can work for me too preferably on the early evening starting at 5pm. I can't do 13th to 15th of Jan cause I have exams and deadlines on those days. I can't do 1st of Jan as well.

**Comment by TheCodeSummoner** [comment]
Wednesday 06/01/2021 6 pm works for people? @lestherll @ymber @NekTaf @Fisherchloe @mradzikowski @EldianTitan

**Comment by ymber** [comment]
That would work for me.

**Comment by lestherll** [comment]
Works for me too.

**Comment by mradzikowski** [comment]
> Wednesday 06/01/2021 6 pm works for people? @lestherll @ymber @NekTaf @Fisherchloe @mradzikowski @EldianTitan

It should work for me!

**Comment by Fisherchloe** [comment]
Works for me

**Comment by p2jason** [comment]
> 
> 
> Wednesday 06/01/2021 6 pm works for people? @lestherll @ymber @NekTaf @Fisherchloe @mradzikowski @EldianTitan

Works fine for me

**Comment by TheCodeSummoner** [comment]
First meeting Wednesday **_06/01/2021 6pm_** confirmed then!
