### ISSUE TITLE
Research and pick the automated unit testing model/tool

### ISSUE THREAD

**Issue by TheCodeSummoner** [ncl-ROVers/surface#37]
To read about possible unit testing tools for Python development which include an automatic tests execution and coverage analysis.

**Comment by ConnorH2525** [comment]
There is a choice of using basic unittest (integrated into python), using nose2 as an extension to unittest (nose1 is no longer maintained), or using pytest.

unittest - gets difficult to understand and use output when hundreds/thousands of tests are created.

pytest - supports filtering test cases and rerunning from last failed test. Has access to plenty of plugins for additional functionality.

**Comment by TheCodeSummoner** [comment]
We will be using pytest.
