### ISSUE TITLE
Logging - function call inspection

### ISSUE THREAD

**Issue by TheCodeSummoner** [ncl-ROVers/surface#45]
To add the following functionality to verbose logging:

1. Which module called it?
2. Was it inside a function? Which one if so? Was it a nested function - nested in what (be careful here - this might actually evolve into a very long chain and be un-readable - only log the last function in that case)?
3. Which exact line of code is this log statement from?

**Comment by jtwil** [comment]
The rough start we made: https://github.com/ncl-ROVers/surface/compare/master...logging-function-call-inspection

**Comment by TheCodeSummoner** [comment]
When will this issue be done and safe to close? I think for function call inspection only the docs and removal of some now-outdated TODO comments is left. Can we finish this up this weekend and start working on the hardware logging please?

**Comment by jtwil** [comment]
>  I think for function call inspection only the docs and removal of some now-outdated TODO comments is left

Yes, other than the issue with your (2) in the OP, which we've mentioned in a chat. @AndMcL is on with the docs required atm. Once he's done with that, the branch should be ready to merge.

We'll start on hardware logging once that's done.
