### ISSUE TITLE
Redesign the menu buttons

### ISSUE THREAD

**Issue by TheCodeSummoner** [ncl-ROVers/surface#51]
The 3 buttons on the top left corner are not enough, we will have more screens. An alternative method should be proposed (typical 3-line button + slide pane from left-hand side?)

**Comment by rudolfs112** [comment]
![menu](https://user-images.githubusercontent.com/57711289/68889876-b7591e00-0715-11ea-8b98-c1c91c94050d.jpg)
New menu design.
