### ISSUE TITLE
Redesign the connections panel

### ISSUE THREAD

**Issue by TheCodeSummoner** [ncl-ROVers/surface#52]
To propose an alternative, more adjustable panel for displaying the connection's status. Each connection is between two devices, and its status is either connected or disconnected. We might have another status for reconnecting, but not confirmed as of now. Colours to distinguish the connection status would be great!

**Comment by rudolfs112** [comment]
![Links 2 0](https://user-images.githubusercontent.com/57711289/68889759-706b2880-0715-11ea-8a52-284e397370f6.jpg)
5 slots for connection status. Red - disconnected, Green - connected, Orange - reconnecting

**Comment by TheCodeSummoner** [comment]
Nobody seems to say anything but I was thinking we could perhaps go with different colour schemas. I feel like the colours are very vivid and contrast a lot with the rest of the GUI, I don't want my attention to be constantly drawn to them.

Perhaps we could have the "Connected" one to match the standard colour (No green, just plain major colour)? This way red and orange should stand out way more!

**Comment by TheCodeSummoner** [comment]
Any thoughts @rudolfs112?

**Comment by rudolfs112** [comment]
![Links 2 0](https://user-images.githubusercontent.com/57711289/71770230-3141a280-2f22-11ea-9882-c3cdc75ceace.jpg)
Is that what you wanted? Do you want me to turn down a little bit the contrast for red and orange?

**Comment by TheCodeSummoner** [comment]
Yes, this is perfect. And no, there is no need for changing the other colours :)
