### ISSUE TITLE
Log hardware state with a different logger

### ISSUE THREAD

**Issue by TheCodeSummoner** [ncl-ROVers/surface#57]
To log hardware and process information with a new hardware logger.

1. Create a new JSON config file.
2. Create needed File handlers.
3. Add functions to the static Log class which use the hardware logger.

Values to log should include the number of processes and threads, current processor load for each processor, GPU and RAM loads. Note that for processes and threads you must make sure that only the relevant ones are counted (the ones spawned directly by our application).

Note: these functions will be called periodically within the GUI for debugging purposes, similar to how the system task managers display the information.

**Comment by jtwil** [comment]
@TheCodeSummoner please see https://github.com/ncl-ROVers/surface/compare/master...hardware-logger for the start we made. Please 6ada7548f916cab7f7203ef8b059dbd39400495f commit message for the stuff left to do.

**Comment by TheCodeSummoner** [comment]
Okay, I thought about how exactly will we use those functionalities in other places, therefore a few notes and adjustments to the plan:

1. I really don't want to have that `hardware_file_handler.py`, unfortunately you will have to remove it.
2. The JSON config file could simply take time + message as format, and then the message passed should already be formatted. The handler can then use a standard file handler instead of the custom one.
3. Let's have only 1 public method get_hardware instead, which will call each sub-method and return all the results. The trick is to construct a message there, and log it with the hardware logger. Then Log.hardware must be documented correctly and say the message must be formatted, the results will go to the hardware.log file etc. etc.

A quick sample what I mean with point 3:
```
def get_hardware_info() -> v1, v2, v3, v4:
    v1 = _get_v1()
    v2 = _get_v2()
    ...
    Log.hardware("\t".join((v1, v2, v3, v4)))
    return v1, v2, v3, v4
```

Additionally, try to keep attention to styling! If you use PyCharm, you will get notified about styling issues, but generally things like spacing between structures, correct type hints, snake case etc. - I will comment all of the missed ones when you submit a PR (pull request)
