### ISSUE TITLE
Add conversion of values from normalised to target

### ISSUE THREAD

**Issue by TheCodeSummoner** [ncl-ROVers/surface#59]
With the control model implemented, it is now time to create mappings of normalised values to expected hardware ranges (and the associated code to handle it nicely).

**Comment by antoinepetty** [comment]
Assuming direct control of the microsecond PWM values, and that the ROV uses the same Thrusters/Motors as 2018/19, the expected ranges are:
Thrusters: 1100-1900
Arm Gripper: 1100-1900
Arm Rotation: 1350 - 1650
Box release(?): 1400 - 1600

**Comment by TheCodeSummoner** [comment]
I might actually leave out the exact values because of the question mark. Are we sticking to the same (Key, Value) based approach? I could serialise it into a sequential list of values from PI level instead, so there is less code on the Arduinos for data parsing.

**Comment by antoinepetty** [comment]
Currently the code is using the same string keys as last year.
Could replace with serialised version as long as there's a concrete list of indexes to devices

**Comment by TheCodeSummoner** [comment]
Surface-side main thrusters implemented.

**Comment by TheCodeSummoner** [comment]
Discussion finished, just waiting for final values now
